name: Build RSDKv5

on:
  push:
    paths:
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  v5-windows-x64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          cache: true
          install: >-
            pkg-config 
            make 
            git 
            mingw-w64-x86_64-gcc 
            mingw-w64-x86_64-SDL2 
            mingw-w64-x86_64-libogg 
            mingw-w64-x86_64-libtheora

      - name: Build RSDKv5 + U
        run: |
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig"
          
          # Force the compiler to look inside our new steam_sdk folder for headers
          export CFLAGS="-I../../steam_sdk"
          export CXXFLAGS="-I../../steam_sdk"
          
          # Compiles with Steam features fully active
          make RSDK_ONLY=1 RSDK_REVISION=3

      - name: Move artifacts
        run: |
          mkdir -p artifacts
          cp ./bin/Windows/DX9/*.exe ./artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v5-windows-x64
          path: artifacts
